### ISSUE TITLE
Provisioning of laprimaire_2022 fails during the task "Allow the HTTP (80) port"

### ISSUE THREAD

**Issue by jerome-caucat** [democratech/2022#28]
# How to reproduce

- Run `vagrant up` for the first time.

# Actual result

- The provisioning of `laprimaire_2022` fails during the task "Allow the HTTP (80) port":
    ```
    TASK [Allow the HTTP (80) port] ************************************************
    fatal: [laprimaire_2022]: FAILED! => {"changed": false, "commands": ["/usr/sbin/ufw status verbose", "/usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules", "/usr/sbin/ufw --version", "/usr/sbin/ufw allow from any to any port 80"], "msg": "ERROR: initcaps\n[Errno 2] Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n\n"}
    ```
    [vagrant-up.log](https://github.com/democratech/2022/files/6259181/vagrant-up.log)

# Expected result

- Successful `vagrant up`.

# Notes

- Provisioning was successful after provisioning a second time with:
    `vagrant reload --provision`

**Comment by JMLX42** [comment]
@jerome-caucat can you please checkout `https://github.com/democratech/2022/tree/20-ekf-stack` and see if the problem persists?

If it works as expected, please close this issue.

**Comment by JMLX42** [comment]
@jerome-caucat the corresponding PR has been merged. Please `git pull` and `vagrant provision`.
