### ISSUE TITLE
Add the ansible_managed comment on all templates

### ISSUE THREAD

**Issue by JMLX42** [democratech/2022#45]
- [ ] `provisioning/roles/laprimaire.blog/templates/analytics.js.j2`
- [ ] `provisioning/roles/laprimaire.blog/templates/docker-compose.yml.j2`
- [ ] `provisioning/roles/laprimaire.logs/templates/docker-compose.yml.j2`
- [ ] `provisioning/roles/laprimaire.forum/templates/docker-compose.yml.j2`
- [ ] `provisioning/roles/laprimaire.monitoring/templates/alert.rules.j2`
- [ ] `provisioning/roles/laprimaire.monitoring/templates/prometheus.yml.j2`
- [ ] `provisioning/roles/laprimaire.monitoring/templates/grafana.ini.j2`
- [ ] `provisioning/roles/laprimaire.monitoring/templates/docker-compose.yml.j2`
- [ ] `provisioning/roles/laprimaire.reverse-proxy/templates/vouch_location.conf.j2`
- [ ] `provisioning/roles/laprimaire.reverse-proxy/templates/vouch.conf.j2`
- [ ] `provisioning/roles/laprimaire.reverse-proxy/templates/docker-compose.yml.j2`
- [ ] `provisioning/roles/laprimaire.analytics/templates/docker-compose.yml.j2`

**Comment by ThomasVille** [comment]
@JMLX42 Can I work on this?
